name: Deploy Nightly
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  nightly:
    name: Deploy nightly
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: nightly zip
        run: zip nightly.zip ./* -r 
      - name: nightly release
        if: matrix.os == 'windows-latest'
        uses: WebFreak001/deploy-nightly@v3.1.0
        with:
          upload_url: https://uploads.github.com/repos/notrogan/FirstPersonDeath/releases/182378275/assets{?name,label}
          release_id: 182378275
          asset_path: ./nightly.zip
          asset_name: nightly-$$.zip
          asset_content_type: application/zip
          max_releases: 365
          ignore_hash: true
